eval $(ssh-agent) &> /dev/null
ssh-add /root/.ssh/id_rsa &> /dev/null

cat <<EOF
Welcome to Jepsen on Docker
===========================

This is the control container that runs the Jepsen tests.

You are currently in the base dir of the git repo for jepsen-docker-workaround.

To run a test:
   
   lein run test

EOF

cd /jepsen
